import type { ScaleShapePosition } from '../types/music.js';

export const SCALE_SHAPE_POSITIONS: ScaleShapePosition[] = [
  // ── Minor Pentatonic ─────────────────────────────────────────────
  {
    id: 'pentatonic-minor-pos1',
    name: 'Minor Pentatonic Pos 1',
    scaleType: 'pentatonic-minor',
    position: 1,
    description: 'The most common pentatonic shape, root on low E string',
    usage: 'Essential for rock, blues, and metal solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 5, fretOffset: 3, degree: 3 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 3, fretOffset: 0, degree: 7 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 2, fretOffset: 0, degree: 3 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 1, fretOffset: 3, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
      { string: 0, fretOffset: 3, degree: 3 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'pentatonic-minor-pos2',
    name: 'Minor Pentatonic Pos 2',
    scaleType: 'pentatonic-minor',
    position: 2,
    description: 'Second position, root on D string',
    usage: 'Connects to position 1 for extended runs',
    pattern: [
      { string: 5, fretOffset: 3, degree: 3 },
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 4, fretOffset: 5, degree: 7 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 3, fretOffset: 5, degree: 3 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 1, fretOffset: 3, degree: 7 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 0, fretOffset: 3, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 3, fretOffset: 2 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'pentatonic-minor-pos3',
    name: 'Minor Pentatonic Pos 3',
    scaleType: 'pentatonic-minor',
    position: 3,
    description: 'Third position, root on A string',
    usage: 'Great for mid-neck soloing',
    pattern: [
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 4, fretOffset: 5, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 3, fretOffset: 5, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 2, fretOffset: 7, degree: 7 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 1, fretOffset: 8, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
      { string: 0, fretOffset: 7, degree: 5 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'pentatonic-minor-pos4',
    name: 'Minor Pentatonic Pos 4',
    scaleType: 'pentatonic-minor',
    position: 4,
    description: 'Fourth position, root on A and G strings',
    usage: 'Upper register pentatonic playing',
    pattern: [
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 5, fretOffset: 10, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 4, fretOffset: 10, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 3, fretOffset: 9, degree: 5 },
      { string: 2, fretOffset: 7, degree: 7 },
      { string: 2, fretOffset: 9, degree: 1 },
      { string: 1, fretOffset: 8, degree: 3 },
      { string: 1, fretOffset: 10, degree: 4 },
      { string: 0, fretOffset: 7, degree: 5 },
      { string: 0, fretOffset: 10, degree: 7 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 2, fretOffset: 9 },
    ],
  },
  {
    id: 'pentatonic-minor-pos5',
    name: 'Minor Pentatonic Pos 5',
    scaleType: 'pentatonic-minor',
    position: 5,
    description: 'Fifth position, connects back to position 1',
    usage: 'Wraps around below position 1 for full neck coverage',
    pattern: [
      { string: 5, fretOffset: -2, degree: 7 },
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 4, fretOffset: -2, degree: 3 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 3, fretOffset: -3, degree: 5 },
      { string: 3, fretOffset: 0, degree: 7 },
      { string: 2, fretOffset: -3, degree: 1 },
      { string: 2, fretOffset: 0, degree: 3 },
      { string: 1, fretOffset: -2, degree: 4 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 0, fretOffset: -2, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 2, fretOffset: -3 },
      { string: 0, fretOffset: 0 },
    ],
  },

  // ── Major Pentatonic ─────────────────────────────────────────────
  {
    id: 'pentatonic-major-pos1',
    name: 'Major Pentatonic Pos 1',
    scaleType: 'pentatonic-major',
    position: 1,
    description: 'Major pentatonic shape with root on low E string',
    usage: 'Great for country, folk, and uplifting solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 5, fretOffset: 2, degree: 2 },
      { string: 4, fretOffset: -1, degree: 3 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 3, fretOffset: -1, degree: 6 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 2, fretOffset: -1, degree: 2 },
      { string: 2, fretOffset: 1, degree: 3 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 1, fretOffset: 2, degree: 6 },
      { string: 0, fretOffset: 0, degree: 1 },
      { string: 0, fretOffset: 2, degree: 2 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'pentatonic-major-pos2',
    name: 'Major Pentatonic Pos 2',
    scaleType: 'pentatonic-major',
    position: 2,
    description: 'Second position, root on D string',
    usage: 'Bright major sound in the mid-neck',
    pattern: [
      { string: 5, fretOffset: 2, degree: 2 },
      { string: 5, fretOffset: 4, degree: 3 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 4, fretOffset: 4, degree: 6 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 3, fretOffset: 4, degree: 2 },
      { string: 2, fretOffset: 1, degree: 3 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 1, fretOffset: 2, degree: 6 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 0, fretOffset: 2, degree: 2 },
      { string: 0, fretOffset: 4, degree: 3 },
    ],
    span: 4,
    rootPositions: [
      { string: 3, fretOffset: 2 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'pentatonic-major-pos3',
    name: 'Major Pentatonic Pos 3',
    scaleType: 'pentatonic-major',
    position: 3,
    description: 'Third position, root on A string',
    usage: 'Useful for connecting positions across the neck',
    pattern: [
      { string: 5, fretOffset: 4, degree: 3 },
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 4, fretOffset: 4, degree: 6 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 3, fretOffset: 4, degree: 2 },
      { string: 3, fretOffset: 6, degree: 3 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 2, fretOffset: 6, degree: 6 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 1, fretOffset: 7, degree: 2 },
      { string: 0, fretOffset: 4, degree: 3 },
      { string: 0, fretOffset: 7, degree: 5 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'pentatonic-major-pos4',
    name: 'Major Pentatonic Pos 4',
    scaleType: 'pentatonic-major',
    position: 4,
    description: 'Fourth position, root on A and G strings',
    usage: 'Upper register major pentatonic playing',
    pattern: [
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 5, fretOffset: 9, degree: 6 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 4, fretOffset: 9, degree: 2 },
      { string: 3, fretOffset: 6, degree: 3 },
      { string: 3, fretOffset: 9, degree: 5 },
      { string: 2, fretOffset: 6, degree: 6 },
      { string: 2, fretOffset: 9, degree: 1 },
      { string: 1, fretOffset: 7, degree: 2 },
      { string: 1, fretOffset: 9, degree: 3 },
      { string: 0, fretOffset: 7, degree: 5 },
      { string: 0, fretOffset: 9, degree: 6 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 2, fretOffset: 9 },
    ],
  },
  {
    id: 'pentatonic-major-pos5',
    name: 'Major Pentatonic Pos 5',
    scaleType: 'pentatonic-major',
    position: 5,
    description: 'Fifth position, connects back to position 1',
    usage: 'Wraps around below position 1',
    pattern: [
      { string: 5, fretOffset: -3, degree: 6 },
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 4, fretOffset: -3, degree: 2 },
      { string: 4, fretOffset: -1, degree: 3 },
      { string: 3, fretOffset: -3, degree: 5 },
      { string: 3, fretOffset: -1, degree: 6 },
      { string: 2, fretOffset: -3, degree: 1 },
      { string: 2, fretOffset: -1, degree: 2 },
      { string: 1, fretOffset: -3, degree: 3 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 0, fretOffset: -3, degree: 6 },
      { string: 0, fretOffset: 0, degree: 1 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 2, fretOffset: -3 },
      { string: 0, fretOffset: 0 },
    ],
  },

  // ── Blues ─────────────────────────────────────────────────────────
  {
    id: 'blues-pos1',
    name: 'Blues Pos 1',
    scaleType: 'blues',
    position: 1,
    description: 'Minor pentatonic with the b5 blue note added',
    usage: 'Essential for blues, rock, and soul solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 5, fretOffset: 3, degree: 3 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 4, fretOffset: 1, degree: 5 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 3, fretOffset: 0, degree: 7 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 2, fretOffset: 0, degree: 3 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 1, fretOffset: 3, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
      { string: 0, fretOffset: 3, degree: 3 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'blues-pos2',
    name: 'Blues Pos 2',
    scaleType: 'blues',
    position: 2,
    description: 'Second blues position with blue note on G string',
    usage: 'Extends blues vocabulary up the neck',
    pattern: [
      { string: 5, fretOffset: 3, degree: 3 },
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 4, fretOffset: 5, degree: 7 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 3, fretOffset: 5, degree: 3 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 2, fretOffset: 3, degree: 5 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 1, fretOffset: 3, degree: 7 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 0, fretOffset: 3, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 3, fretOffset: 2 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'blues-pos3',
    name: 'Blues Pos 3',
    scaleType: 'blues',
    position: 3,
    description: 'Third blues position with blue notes on E strings',
    usage: 'Mid-neck blues with multiple blue note options',
    pattern: [
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 5, fretOffset: 6, degree: 5 },
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 4, fretOffset: 5, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 3, fretOffset: 5, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 2, fretOffset: 7, degree: 7 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 1, fretOffset: 8, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
      { string: 0, fretOffset: 6, degree: 5 },
      { string: 0, fretOffset: 7, degree: 5 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'blues-pos4',
    name: 'Blues Pos 4',
    scaleType: 'blues',
    position: 4,
    description: 'Fourth blues position with blue note on D string',
    usage: 'Upper register blues playing',
    pattern: [
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 5, fretOffset: 10, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 4, fretOffset: 10, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 3, fretOffset: 8, degree: 5 },
      { string: 3, fretOffset: 9, degree: 5 },
      { string: 2, fretOffset: 7, degree: 7 },
      { string: 2, fretOffset: 9, degree: 1 },
      { string: 1, fretOffset: 8, degree: 3 },
      { string: 1, fretOffset: 10, degree: 4 },
      { string: 0, fretOffset: 7, degree: 5 },
      { string: 0, fretOffset: 10, degree: 7 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 2, fretOffset: 9 },
    ],
  },
  {
    id: 'blues-pos5',
    name: 'Blues Pos 5',
    scaleType: 'blues',
    position: 5,
    description: 'Fifth blues position, connects back to position 1',
    usage: 'Wraps around below position 1 with blue note on B string',
    pattern: [
      { string: 5, fretOffset: -2, degree: 7 },
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 4, fretOffset: -2, degree: 3 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 3, fretOffset: -3, degree: 5 },
      { string: 3, fretOffset: 0, degree: 7 },
      { string: 2, fretOffset: -3, degree: 1 },
      { string: 2, fretOffset: 0, degree: 3 },
      { string: 1, fretOffset: -2, degree: 4 },
      { string: 1, fretOffset: -1, degree: 5 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 0, fretOffset: -2, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 2, fretOffset: -3 },
      { string: 0, fretOffset: 0 },
    ],
  },

  // ── Major Scale ──────────────────────────────────────────────────
  {
    id: 'major-pos1',
    name: 'Major Scale Pos 1',
    scaleType: 'major',
    position: 1,
    description: 'E-shape major scale with root on low E string',
    usage: 'Foundation for major key lead playing and melody',
    pattern: [
      { string: 5, fretOffset: -1, degree: 7 },
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 5, fretOffset: 2, degree: 2 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 3, fretOffset: -1, degree: 6 },
      { string: 3, fretOffset: 1, degree: 7 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 2, fretOffset: -1, degree: 2 },
      { string: 2, fretOffset: 1, degree: 3 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 1, fretOffset: -2, degree: 4 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 1, fretOffset: 2, degree: 6 },
      { string: 0, fretOffset: -1, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
      { string: 0, fretOffset: 2, degree: 2 },
    ],
    span: 5,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'major-pos2',
    name: 'Major Scale Pos 2',
    scaleType: 'major',
    position: 2,
    description: 'D-shape major scale position',
    usage: 'Connects position 1 to position 3',
    pattern: [
      { string: 5, fretOffset: 2, degree: 2 },
      { string: 5, fretOffset: 4, degree: 3 },
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 4, fretOffset: 2, degree: 5 },
      { string: 4, fretOffset: 4, degree: 6 },
      { string: 3, fretOffset: 2, degree: 1 },
      { string: 3, fretOffset: 4, degree: 2 },
      { string: 2, fretOffset: 2, degree: 4 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 1, fretOffset: 2, degree: 6 },
      { string: 1, fretOffset: 4, degree: 7 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 0, fretOffset: 2, degree: 2 },
      { string: 0, fretOffset: 4, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 3, fretOffset: 2 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'major-pos3',
    name: 'Major Scale Pos 3',
    scaleType: 'major',
    position: 3,
    description: 'C-shape major scale position',
    usage: 'Mid-neck position for melodic playing',
    pattern: [
      { string: 5, fretOffset: 4, degree: 3 },
      { string: 5, fretOffset: 5, degree: 4 },
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 4, fretOffset: 4, degree: 6 },
      { string: 4, fretOffset: 6, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 3, fretOffset: 4, degree: 2 },
      { string: 3, fretOffset: 6, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 2, fretOffset: 4, degree: 5 },
      { string: 2, fretOffset: 6, degree: 6 },
      { string: 1, fretOffset: 5, degree: 1 },
      { string: 1, fretOffset: 7, degree: 2 },
      { string: 0, fretOffset: 4, degree: 3 },
      { string: 0, fretOffset: 5, degree: 4 },
      { string: 0, fretOffset: 7, degree: 5 },
    ],
    span: 4,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 1, fretOffset: 5 },
    ],
  },
  {
    id: 'major-pos4',
    name: 'Major Scale Pos 4',
    scaleType: 'major',
    position: 4,
    description: 'A-shape major scale position',
    usage: 'Upper register major scale playing',
    pattern: [
      { string: 5, fretOffset: 7, degree: 5 },
      { string: 5, fretOffset: 9, degree: 6 },
      { string: 5, fretOffset: 11, degree: 7 },
      { string: 4, fretOffset: 7, degree: 1 },
      { string: 4, fretOffset: 9, degree: 2 },
      { string: 4, fretOffset: 11, degree: 3 },
      { string: 3, fretOffset: 7, degree: 4 },
      { string: 3, fretOffset: 9, degree: 5 },
      { string: 3, fretOffset: 11, degree: 6 },
      { string: 2, fretOffset: 8, degree: 7 },
      { string: 2, fretOffset: 9, degree: 1 },
      { string: 2, fretOffset: 11, degree: 2 },
      { string: 1, fretOffset: 7, degree: 2 },
      { string: 1, fretOffset: 9, degree: 3 },
      { string: 1, fretOffset: 10, degree: 4 },
      { string: 0, fretOffset: 7, degree: 5 },
      { string: 0, fretOffset: 9, degree: 6 },
      { string: 0, fretOffset: 11, degree: 7 },
    ],
    span: 5,
    rootPositions: [
      { string: 4, fretOffset: 7 },
      { string: 2, fretOffset: 9 },
    ],
  },
  {
    id: 'major-pos5',
    name: 'Major Scale Pos 5',
    scaleType: 'major',
    position: 5,
    description: 'G-shape major scale, connects back to position 1',
    usage: 'Lower position wrapping below position 1',
    pattern: [
      { string: 5, fretOffset: -3, degree: 6 },
      { string: 5, fretOffset: -1, degree: 7 },
      { string: 5, fretOffset: 0, degree: 1 },
      { string: 4, fretOffset: -3, degree: 2 },
      { string: 4, fretOffset: -1, degree: 3 },
      { string: 4, fretOffset: 0, degree: 4 },
      { string: 3, fretOffset: -3, degree: 5 },
      { string: 3, fretOffset: -1, degree: 6 },
      { string: 2, fretOffset: -4, degree: 7 },
      { string: 2, fretOffset: -3, degree: 1 },
      { string: 2, fretOffset: -1, degree: 2 },
      { string: 1, fretOffset: -3, degree: 3 },
      { string: 1, fretOffset: -2, degree: 4 },
      { string: 1, fretOffset: 0, degree: 5 },
      { string: 0, fretOffset: -3, degree: 6 },
      { string: 0, fretOffset: -1, degree: 7 },
      { string: 0, fretOffset: 0, degree: 1 },
    ],
    span: 5,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 2, fretOffset: -3 },
      { string: 0, fretOffset: 0 },
    ],
  },
];
