import type { ScaleShapePosition } from '../types/music.js';

export const SCALE_SHAPE_POSITIONS: ScaleShapePosition[] = [
  {
    id: 'pentatonic-minor-box1',
    name: 'Minor Pentatonic Box 1',
    scaleType: 'pentatonic-minor',
    description: 'The most common pentatonic shape, root on low E string',
    usage: 'Essential for rock, blues, and metal solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1, finger: 1 },
      { string: 5, fretOffset: 3, degree: 3, finger: 4 },
      { string: 4, fretOffset: 0, degree: 4, finger: 1 },
      { string: 4, fretOffset: 2, degree: 5, finger: 3 },
      { string: 3, fretOffset: 0, degree: 7, finger: 1 },
      { string: 3, fretOffset: 2, degree: 1, finger: 3 },
      { string: 2, fretOffset: 0, degree: 3, finger: 1 },
      { string: 2, fretOffset: 2, degree: 4, finger: 3 },
      { string: 1, fretOffset: 0, degree: 5, finger: 1 },
      { string: 1, fretOffset: 3, degree: 7, finger: 4 },
      { string: 0, fretOffset: 0, degree: 1, finger: 1 },
      { string: 0, fretOffset: 3, degree: 3, finger: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'pentatonic-major-box1',
    name: 'Major Pentatonic Box 1',
    scaleType: 'pentatonic-major',
    description: 'Major pentatonic shape with root on low E string',
    usage: 'Great for country, folk, and uplifting solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1, finger: 1 },
      { string: 5, fretOffset: 2, degree: 2, finger: 3 },
      { string: 4, fretOffset: -1, degree: 6, finger: 1 },
      { string: 4, fretOffset: 2, degree: 1, finger: 4 },
      { string: 3, fretOffset: -1, degree: 2, finger: 1 },
      { string: 3, fretOffset: 2, degree: 3, finger: 4 },
      { string: 2, fretOffset: -1, degree: 5, finger: 1 },
      { string: 2, fretOffset: 1, degree: 6, finger: 3 },
      { string: 1, fretOffset: 0, degree: 1, finger: 1 },
      { string: 1, fretOffset: 2, degree: 2, finger: 3 },
      { string: 0, fretOffset: 0, degree: 3, finger: 1 },
      { string: 0, fretOffset: 2, degree: 5, finger: 3 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 4, fretOffset: 2 },
      { string: 1, fretOffset: 0 },
    ],
  },
  {
    id: 'blues-box1',
    name: 'Blues Box 1',
    scaleType: 'blues',
    description: 'Minor pentatonic with the b5 blue note added',
    usage: 'Essential for blues, rock, and soul solos',
    pattern: [
      { string: 5, fretOffset: 0, degree: 1, finger: 1 },
      { string: 5, fretOffset: 3, degree: 3, finger: 4 },
      { string: 4, fretOffset: 0, degree: 4, finger: 1 },
      { string: 4, fretOffset: 1, degree: 5, finger: 2 },
      { string: 4, fretOffset: 2, degree: 5, finger: 3 },
      { string: 3, fretOffset: 0, degree: 7, finger: 1 },
      { string: 3, fretOffset: 2, degree: 1, finger: 3 },
      { string: 2, fretOffset: 0, degree: 3, finger: 1 },
      { string: 2, fretOffset: 2, degree: 4, finger: 3 },
      { string: 1, fretOffset: 0, degree: 5, finger: 1 },
      { string: 1, fretOffset: 3, degree: 7, finger: 4 },
      { string: 0, fretOffset: 0, degree: 1, finger: 1 },
      { string: 0, fretOffset: 3, degree: 3, finger: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
  {
    id: 'major-box1',
    name: 'Major Scale Box 1',
    scaleType: 'major',
    description: 'Movable major scale position with root on low E string',
    usage: 'Foundation for major key lead playing and melody',
    pattern: [
      { string: 5, fretOffset: -1, degree: 7, finger: 1 },
      { string: 5, fretOffset: 0, degree: 1, finger: 2 },
      { string: 5, fretOffset: 2, degree: 2, finger: 4 },
      { string: 4, fretOffset: 0, degree: 4, finger: 1 },
      { string: 4, fretOffset: 2, degree: 5, finger: 3 },
      { string: 3, fretOffset: -1, degree: 6, finger: 1 },
      { string: 3, fretOffset: 1, degree: 7, finger: 3 },
      { string: 3, fretOffset: 2, degree: 1, finger: 4 },
      { string: 2, fretOffset: -1, degree: 2, finger: 1 },
      { string: 2, fretOffset: 1, degree: 3, finger: 3 },
      { string: 2, fretOffset: 2, degree: 4, finger: 4 },
      { string: 1, fretOffset: -1, degree: 3, finger: 1 },
      { string: 1, fretOffset: 0, degree: 4, finger: 2 },
      { string: 1, fretOffset: 2, degree: 5, finger: 4 },
      { string: 0, fretOffset: -1, degree: 7, finger: 1 },
      { string: 0, fretOffset: 0, degree: 1, finger: 2 },
      { string: 0, fretOffset: 2, degree: 2, finger: 4 },
    ],
    span: 4,
    rootPositions: [
      { string: 5, fretOffset: 0 },
      { string: 3, fretOffset: 2 },
      { string: 0, fretOffset: 0 },
    ],
  },
];
